name: Getting shared files between steps

on: 
  workflow_dispatch

jobs:
  between-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu version checking
        run: cat /etc/os-release
      
      - name: Saving text message
        run: echo "This is a test message." > message.txt

      - name: Listing files
        run: ls -lha

      - name: Reading a message
        run: cat message.txt