name: Getting shared files between jobs

on: 
 workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu version checking
        run: cat /etc/os-release
      
      - name: Saving text message
        run: echo "This is a test message." > ${{ github.workspace }}/message.txt

      - uses: actions/upload-artifact@v4
        with:
          name: files-upload
          path:  ${{ github.workspace }}/message.txt



  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Listing directory content
        run: ls -lha

      - uses: actions/download-artifact@v4
        with:
          name: files-upload
          path: files

      - name: Listing directory files
        run: ls -lha && ls ./files/

      - name: Reading a message
        run: cat files/message.txt