name: Getting shared files between jobs

on: 
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu version checking
        run: cat /etc/os-release
      
      - name: Saving text message
        run: echo "This is a test message." > /home/ubuntu/message.txt

      - uses: actions/upload-artifact@v4
        with:
          name: files
          path: /home/ubuntu/message.txt



  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Listing directory content
        run: ls -lha

      - uses: actions/download-artifact@v4
        with:
          name: files
          path: message.txt

      - name: Listing directory files
        run: ls -lha && ls ./files/

      - name: Reading a message
        run: cat files/message.txt