name: First Worflow

on: 
  workflow_dispatch

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu version checking
        run: cat /etc/os-release
      
      - name: Showing a message
        run: echo "This is a test message."