name: First Worflow

on: 
  push:
    branches:
      - main

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu version checking
        run: cat /etc/os-release
      
      - name: Showing a message
        run: echo "This is a test message." > message.txt

      - name: Listing files
        run: ls -lha

      - name: Reading a message
        run: cat message.txt